function createfigure(XData1, YData1, XData2, YData2, XData3, YData3, YData4)
%CREATEFIGURE(XDATA1, YDATA1, XDATA2, YDATA2, XDATA3, YDATA3, YDATA4)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  XDATA3:  line xdata
%  YDATA3:  line ydata
%  YDATA4:  line ydata

%  Auto-generated by MATLAB on 15-Dec-2015 14:46:13

% Create figure
figure1 = figure('Name','Linear Analysis Tool Plot: Bode Plot 1');

% Create xlabel
xlabel('Frequency  (Hz)','Units','normalized',...
    'HorizontalAlignment','center',...
    'FontSize',11,...
    'Visible','on');

% Create title
title('Bode Diagram','Units','normalized','HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',11);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.147241379310345 0.11 0.757758620689655 0.353149403578529]);

% Create line
line(XData1,YData1,'Visible','off','Parent',axes1);

% Create hggroup
hggroup1 = hggroup('Parent',axes1,'DisplayName','linsys1','Tag','');

% Create line
line(XData2,YData2,'Parent',hggroup1,'Color',[0 0.447 0.741]);

% Create ylabel
ylabel('Phase (deg)','Units','normalized','FontSize',11);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.1 100]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-727.2 7.2]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XColor',[0.4 0.4 0.4],'XScale','log','YColor',[0.4 0.4 0.4],...
    'YTick',[-720 -540 -360 -180 0]);
% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.147241379310345 0.487006262425447 0.757758620689655 0.398232306163022]);

% Create line
line(XData3,YData3,'Visible','off','Parent',axes2);

% Create hggroup
hggroup2 = hggroup('Parent',axes2,'DisplayName','linsys1','Tag','');

% Create line
line(XData2,YData4,'Parent',hggroup2,'Color',[0 0.447 0.741]);

% Create ylabel
ylabel('Magnitude (dB)','Units','normalized','FontSize',11);

% Create title
title('From: Step  To: Discrete Filter','Units','normalized',...
    'Color',[0.4 0.4 0.4]);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0.1 100]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[-400 100]);
box(axes2,'on');
% Set the remaining axes properties
set(axes2,'XColor',[0.4 0.4 0.4],'XScale','log','XTickLabel','','YColor',...
    [0.4 0.4 0.4]);
% Create legend
legend1 = legend(axes2,'show');
set(legend1,...
    'Position',[0.736169268333898 0.811581306857555 0.166071426602347 0.0507936496583242]);

